import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { getMyShop } from '../../services/shop.api';
import { createShopVoucher, fetchShopVouchers } from '../../services/voucher.api';

export default function SellerVoucherManagement() {
  const [shopId, setShopId] = useState(''); const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState({ code: '', name: '', percentage: '10', minOrderAmount: '0', startsAt: '', endsAt: '' });
  const load = async (id: string) => { try { setItems(await fetchShopVouchers(id)); } catch (error) { toast.error(error instanceof Error ? error.message : 'Khong the tai voucher'); } };
  useEffect(() => { void getMyShop().then((shop) => { const id = shop?.id ?? shop?.shopId; if (id) { setShopId(id); void load(id); } }); }, []);
  const create = async () => { if (!shopId) return; try { await createShopVoucher(shopId, { ...form, percentage: Number(form.percentage), minOrderAmount: Number(form.minOrderAmount), startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString(), discountType: 'PERCENTAGE' }); toast.success('Tao voucher shop thanh cong'); await load(shopId); } catch (error) { toast.error(error instanceof Error ? error.message : 'Khong the tao voucher'); } };
  return <section className="admin-page"><div className="admin-page-heading"><div><h1>Voucher cua shop</h1><p>Tao uu dai va theo doi ma giam gia cua shop.</p></div></div><div className="admin-placeholder-card"><h2>Tao voucher</h2><div className="admin-placeholder-list"><input placeholder="Ma voucher" aria-label="Ma voucher" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /><input placeholder="Ten voucher" aria-label="Ten voucher" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input type="number" placeholder="% giam" aria-label="Phan tram" value={form.percentage} onChange={(e) => setForm({ ...form, percentage: e.target.value })} /><input type="number" placeholder="Don toi thieu" aria-label="Don toi thieu" value={form.minOrderAmount} onChange={(e) => setForm({ ...form, minOrderAmount: e.target.value })} /><input type="datetime-local" aria-label="Bat dau" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /><input type="datetime-local" aria-label="Ket thuc" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} /><button type="button" onClick={create}>Tao voucher</button></div></div><div className="admin-placeholder-card"><h2>Voucher dang co</h2>{items.map((item) => <div className="admin-placeholder-list" key={item.id}><strong>{item.code}</strong><span>{item.name}</span><span>{item.status}</span></div>)}</div></section>;
}
